name: VillageBuilder
version: '1.21-1.0.0'
main: net.elysium.VillageBuilder.Main
api-version: '1.21'
authors: [ UiMi17, S4r3ss ]
website: https://discord.gg/sRy72EhjR8
commands:
  pos:
    description: "Команда для виділення областей структур та стадій"
  createStructure:
    description: "Команда для створення структур"
