name: VillageBuilder
version: '1.21-1.0.0'
main: net.elysium.VillageBuilder.Main
authors: [ UiMi17, S4r3ss ]
website: https://discord.gg/sRy72EhjR8
commands:
  pos:
    description: "Команда для виділення областей структур та стадій"
  create-structure:
    description: "Команда для створення структур"
  assign-stage:
    description: "Команда для створення та присвоювання новостворенної стадії до існуючої структури"
  assign-resources:
    description: "Команда для додавання ресурсів до стадії, необхідних для її досягнення"
